# Generated by Django 5.2.11 on 2026-03-01 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ABACPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('role', models.CharField(max_length=100)),
                ('attribute', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=500)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('elevate', 'Elevate Role'), ('downgrade', 'Downgrade Role')], default='deny', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ABAC Policies',
                'ordering': ['-priority'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(default='anonymous', max_length=255)),
                ('endpoint', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=10)),
                ('role', models.CharField(default='viewer', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('anomaly_score', models.FloatField(default=0.0)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('context_vector', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('actor', models.CharField(default='system', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('block_hash', models.CharField(max_length=64)),
                ('prev_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', max_length=64)),
                ('block_index', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('verified', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RoleAdaptation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_identifier', models.CharField(max_length=255)),
                ('old_role', models.CharField(max_length=100)),
                ('new_role', models.CharField(max_length=100)),
                ('context_vector', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('adapted_by', models.CharField(default='edge', max_length=50)),
                ('from_edge', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
